version: '3'
services:
  selenium_service:
    image: selenium/standalone-chrome
    container_name: container_selenium
    shm_size: 2gb
    ports:
      - 4444:4444

  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
